name: cccc-Clone

on:
  pull_request:
    branches:
      - test

jobs:
  clone:
    runs-on: ubuntu-latest
    steps:
    - name: Modify branch name
      run: |
        echo "cicicicici"


    # - name: Upload Paddle artifact
    #   uses: actions/upload-artifact@v3
    #   with:
    #     name: Paddle
    #     path: Paddle.tar.gz
