name: Re-run

on:
  issue_comment:
    types: [created]

jobs:
  re-run:
    if: ${{ github.event.issue.pull_request && contains(github.event.comment.body, '/re-run') }}
    runs-on: ubuntu-latest
    steps:
      - name: List failed workflows
        id: list_failed
        run: |
          pr_number=${{ github.event.issue.number }}
          curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            "https://api.github.com/repos/${{ github.repository }}/actions/runs?status=failure&branch=${{ github.head_ref }}" | \
            jq --arg pr_number "$pr_number" -r '.workflow_runs | map(select(.pull_requests[].number == ($pr_number | tonumber))) | map({id: .id, name: .name, created_at: .created_at}) | sort_by(.created_at) | reverse | unique_by(.name) | .[].id' > failed_run_ids.txt
          echo "Failed run IDs:"
          cat failed_run_ids.txt

      - name: Re run failed workflows
        run: |
          while IFS= read -r run_id; do
            echo "Re-running workflow with ID: $run_id"
            curl -X POST -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
              "https://api.github.com/repos/${{ github.repository }}/actions/runs/$run_id/rerun"
          done < failed_run_ids.txt
